[tool.poetry]
name = "simple_note_taker"
version = "0.1.2"
description = ""
authors = ["Toby <toby@thedevlins.biz>"]
readme = 'readme.md'

[tool.poetry.scripts]
snt = "simple_note_taker.main:app"

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.3.2"
colorama = "^0.4.4"
tinydb = "^4.4.0"
tinydb-serialization = "^2.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
