name: Testing Flow
on: workflow_dispatch
jobs:
  test_and_build:
    runs-on: ubuntu-latest
    #    container: node:10.18-jessie
    #    services:
    #      postgres:
    #        image: postgres
    strategy:
      matrix:
        python: [ '3.6','3.7','3.8', '3.9' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Setup Python ${{ matrix.python }}
        with:
          python-version: ${{ matrix.python }}
      - run: echo "running python $(python --version) at $(which python)"
      - run: python -m pip install poetry
      - run: poetry install
      - run: poetry run black . --check
      - run: poetry run pytest . --cov-report=xml
      - uses: actions/upload-artifact@v2
        with:
          name: test-coverage-xml
          path: ./coverage.xml
      - run: poetry run build
      - uses: actions/upload-artifact@v2
        with:
          name: build-assets
          path: ./dist/*


